# Numpy Array

In [4]:
import numpy as np

In [2]:
print(dir(np))                     # checking for all the function in numpy

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [3]:
# for square root-np.sqrt(number)
np.sqrt(10)            #square root of 10=3.1622

3.1622776601683795

In [4]:
# Round off-np.ceil()       [it will round off the decimal number to next number]
np.ceil(26.3)

27.0

In [5]:
np.ceil(np.sqrt(10))         # round off the square root of 10=3.162=4.0

4.0

In [7]:
np.ceil(np.sum(np.sqrt([5,10,15])))     #np.sum used for adding and sum 

10.0

In [9]:
# minimum and maximum select from number list
print('Minimum', np.amin([10,25,15,30]))

print('Maximum', np.amax([10,25,15,30]))

Minimum 10
Maximum 30


In [10]:
#Array
np.array([5,9,13])     #array in numpy is as similar as list in python

array([ 5,  9, 13])

In [11]:
type([5,9,13])           #chicking the type

list

In [12]:
xyz=np.array([5,9,13])   # assigning array to xyz

In [13]:
type(xyz)                 # nd= n dimensional

numpy.ndarray

In [14]:
# For two dimensional (2d)
a=np.array([[1,2],[3,4],[4,5]])
print("type-", a.dtype)       #a.dtype tp show the type of number in array
print('\n','*' * 30)
print('\n', a)

type- int32

 ******************************

 [[1 2]
 [3 4]
 [4 5]]


In [16]:
# dtype conersion
np.array([1,2,3], dtype=float)     # Here we coverting integer to float

array([1., 2., 3.])

In [17]:
# Coverting list into an array
a=[1,2]
c=np.array(a)
print(c)

[1 2]


In [18]:
#Copy array
b=np.asarray(c)    # copying c array into b array as it is
print(b)

[1 2]


# Data types

In [20]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)       #coverting into array

print("Type/Class of the object",type(mat))
print("Here is matrix\n-----------\n",mat,"\n-----------")
print("Dimension of Matrix",mat.ndim,sep='')    #ndim used for checking dimension
print("Size of Matrix",mat.size,sep='')         #size is total numbers odf elements
print("Shape of Matrix",mat.shape)            #shape is used to give number of elements at each axis
print("Data type of matrix",mat.dtype)

Type/Class of the object <class 'numpy.ndarray'>
Here is matrix
-----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------
Dimension of Matrix2
Size of Matrix9
Shape of Matrix (3, 3)
Data type of matrix int32


# arange and linespace
In arange both integer and float values are generated which was not happened in range function of python that take only inetgers

In [22]:
# arange
a=list(range(2.,5.5,.4))     # It give error because data have float value in it

TypeError: 'float' object cannot be interpreted as an integer

In [21]:
a=np.arange(2.,5.5,.4)     # Here 2.=start,5.5=stop,.4=step size
a

array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2])

In [23]:
#linspace
print(np.linspace(10,40,5))   #np.linspace(start,stop,number of elemnets in between)

[10.  17.5 25.  32.5 40. ]


In [25]:
#Including endpoint and check point
#by default endpoint=True & retstep=False    (retstep=difference given between thwe elements)
print(np.linspace(2.0, 3.0, num=4, endpoint=False, retstep=True))     #endpoint-Flase means it is not included

(array([2.  , 2.25, 2.5 , 2.75]), 0.25)


In [5]:
np.linspace(4.36256,15.236548,25, retstep=True)

(array([ 4.36256   ,  4.81564283,  5.26872567,  5.7218085 ,  6.17489133,
         6.62797417,  7.081057  ,  7.53413983,  7.98722267,  8.4403055 ,
         8.89338833,  9.34647117,  9.799554  , 10.25263683, 10.70571967,
        11.1588025 , 11.61188533, 12.06496817, 12.518051  , 12.97113383,
        13.42421667, 13.8772995 , 14.33038233, 14.78346517, 15.236548  ]),
 0.4530828333333334)

# Matrix Creation

In [6]:
print("Vector of zeros \n",'*'*15)
print(np.zeros(5))    #Vector of zeros created

Vector of zeros 
 ***************
[0. 0. 0. 0. 0.]


In [8]:
print(np.zeros((5,6)))   # Here is 5=row & 6=column

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [9]:
print("Vector of ones \n",'*'*15)
print(np.ones(5))    #Vector of ones created

Vector of ones 
 ***************
[1. 1. 1. 1. 1.]


In [10]:
print(np.ones((5,6)))   # Here is 5=row & 6=column

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [12]:
print(6*np.ones((5,6)))   # as there is only 0 & 1 so for other number we have to multiply that number.

[[6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6. 6.]]


In [15]:
# Construct diagonal matrix
x=np.arange(30).reshape(5,6)       #number you given must be multiple or set in matrix like 30=5*6,6*5 etc.
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


# Random Number Generation
There re of three types 
1. rand
2. randn
3. randint

In [19]:
np.random.seed(6)   # seed is used for generate similar data otherwise it will change everytime when you run it
print(np.random.rand(10,6))  # 1. In rand all numbers are '+ve',<1,float and uniform(close to each other)

[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [20]:
#randn- numbers are +&-and are in normal distribution
print(np.random.randn(10,3))

[[-0.37550472  0.39636757 -0.47144628]
 [ 2.33660781  1.50278553 -0.59545972]
 [ 0.52834106  0.9398248   0.42628539]
 [-0.75815703 -0.16236698  0.72680996]
 [ 0.44408297 -0.85682264  0.44692842]
 [-1.01464799 -2.1323234   0.17386307]
 [ 0.95120126  0.44189739  1.46901739]
 [ 1.74951635  0.35353062 -0.64333729]
 [-0.04723705 -1.44903979 -0.03618977]
 [-0.09084699  0.17629034  1.09462041]]


In [23]:
#randint-integer numbers are genetrated & all are random =randint(low,High,elements in between)
print(np.random.randint(5,20,10))

[14  8 13  5 12 17 12 18  5  8]


In [25]:
print(np.random.randint(5,20000,(6,6)))   # (6,6) is matrix given. Number must be dawn from this matrix

[[  833 17521  6598  1399  7966  5802]
 [12768 19419  9177  6421 12772 14535]
 [18996 15891 11363 16709 18784 18311]
 [15359 11226 15660  8976   603  3371]
 [   14 16538 12578 19715  7364  7871]
 [ 7197 14023 13024 13081 18983   104]]


In [26]:
# Example of OTP generation
while True:
    otp1=np.random.randint(1000,10000,1)
    print("Your OTP is-", otp1)
    user_otp=int(input('Enter OTP'))
    if otp1==user_otp:
        print('Login sucess')
        break
    else:
        print('Invalid OTP,Genrate new otp')
        continue

Your OTP is- [6099]
Enter OTP6095
Invalid OTP,Genrate new otp
Your OTP is- [6417]
Enter OTP6417
Login sucess


# Reshaping Other Ways

In [27]:
import numpy as np
from numpy.random import randint as ri   #This is for shorting of long formulae of  randint
a=ri(1,99,30)
a             # calling a matrix

array([63, 37, 64, 64, 49,  6, 27, 40, 87, 98, 98, 34, 39, 59, 25, 34, 70,
       42, 93, 14, 30,  3, 83, 12, 85, 59, 40, 34, 22, 68])

In [28]:
c=a.reshape(6,5)   # assigning a matrix to c new matrix of 6 rows and 5 coulmns
c

array([[63, 37, 64, 64, 49],
       [ 6, 27, 40, 87, 98],
       [98, 34, 39, 59, 25],
       [34, 70, 42, 93, 14],
       [30,  3, 83, 12, 85],
       [59, 40, 34, 22, 68]])

In [29]:
#for max and min number in matrix
print('Min -',c.min())
print('Max-',c.max())

Min - 3
Max- 98


In [30]:
c.mean()   #this is the mean of all numbers in matrix c

49.3

# Sorting
It sorted by row and coulmn in ascending order

In [34]:
m=ri(1,100,25).reshape(5,5)
print("\n Random matrix \n", m)
print("\n sorted by row \n", np.sort(m))   #by default axis=1
print("\n sorted by coulmn \n", np.sort(m,axis=0))


 Random matrix 
 [[51 84 84 19 78]
 [48 66 97 70 45]
 [21 17 85 55 50]
 [73 83 85 20 28]
 [ 6 85 61  6 16]]

 sorted by row 
 [[19 51 78 84 84]
 [45 48 66 70 97]
 [17 21 50 55 85]
 [20 28 73 83 85]
 [ 6  6 16 61 85]]

 sorted by coulmn 
 [[ 6 17 61  6 16]
 [21 66 84 19 28]
 [48 83 85 20 45]
 [51 84 85 55 50]
 [73 85 97 70 78]]


# Numpy condition
When there are conditions like(==,<,>,<=,=>,etc) numpy condition apply

In [35]:
emp_salary=np.random.randint(8000,70000,10)
emp_salary

array([18533, 16710, 57563, 68879, 40439, 51498, 46423, 51347, 25443,
       51138])

In [36]:
# Now to find actual salary which are less than or greater than some particular
print(np.where(emp_salary<25000))   # It will give index position of those salaries which are less than 25000 

(array([0, 1], dtype=int64),)


In [37]:
# To fetch salary of those index position are above
emp_salary[np.where(emp_salary<25000)]        # Actual salary less than 25000 displayed

array([18533, 16710])

In [38]:
# To set minimum and maximum limit by giving values
np.clip(emp_salary, a_min=20000, a_max=50000) # slary lower than 20000 will replace by it and higher than 50000 will replace by 50000

array([20000, 20000, 50000, 50000, 40439, 50000, 46423, 50000, 25443,
       50000])

# Indexing and Slicing
It is same as python finding data by index position or to replace and update it.


In [43]:
a=np.arange(13,30)
print("Array:", a)

Array: [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [44]:
print("Element at 7th position:", a[7])

Element at 7th position: 20


In [45]:
print("Element at 2nd,4th and 9th position:", a[[2,4,9]])   #'[[]]' for more than one index postion pass

Element at 2nd,4th and 9th position: [15 17 22]


In [50]:
# TO find index psotion in matrix
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
print("Element at row index 1 and column index 2:", mat[1][2])

Element at row index 1 and column index 2: 6


In [54]:
# print(mat[rowstart:rowend,columnstart:columnend])
print(mat[:,1:])    #empty row means start from 0 end at 2 & 1 is start of column and empty end is 2.

[[2 3]
 [5 6]
 [8 9]]


In [55]:
print(mat[1:2,1:2])

[[5]]


In [58]:
print("",mat[0:2,[1,2]])   # means in 0:2 row you have to display 1,2 column

 [[2 3]
 [5 6]]


###### Update Matrix

In [59]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
mat[1][2]=50

In [61]:
mat    # 6 replaced or updated by 50

array([[ 1,  2,  3],
       [ 4,  5, 50],
       [ 7,  8,  9]])

In [62]:
mat[1][0]=56
mat

array([[ 1,  2,  3],
       [56,  5, 50],
       [ 7,  8,  9]])

# Subseting

In [63]:
mat=np.array(ri(10,100,15)).reshape(3,5)
mat     #creating matrix

array([[91, 64, 33, 73, 68],
       [29, 28, 81, 36, 67],
       [37, 30, 36, 90, 67]])

In [64]:
mat>50    # it will give boolean

array([[ True,  True, False,  True,  True],
       [False, False,  True, False,  True],
       [False, False, False,  True,  True]])

In [65]:
mat[mat>50]    # now it will givw integer values greater than 50

array([91, 64, 73, 68, 81, 67, 90, 67])

In [66]:
# use of np.where
marks=50
np.where(marks>60,'pass','fail')

array('fail', dtype='<U4')

In [67]:
marks=75
np.where(marks>60,'pass','fail')

array('pass', dtype='<U4')

In [71]:
# Check for non zero
non_zero=ri(-10,50,100)
print(non_zero)
np.count_nonzero(non_zero)

[ 11  22  26  14  29  38  13  24  47   3  37  36  -5  -9  42  25  -7  -5
  25   8  -7  32  12   8  18 -10   0  10  11  26  -7  -9  -5  26  45  -3
  16   0   5  46  41  -1  29  16  44  41  11  -5  42  16  38  24   2  43
  16  37  16  27 -10  39  15  34  30   3   3   7  46  24   9  35  43  31
   9  -1  21   0  45  45  45  22  -4  31  -3  15   8  24  27  28  14  30
  47   0  31  10  11  30  12  39   9   8]


96

In [74]:
#Ravel and Flattern(deep learning concepts for image processing)
a=np.random.randint(0,20,size=(3,4))
a

array([[19, 15, 17,  1],
       [17, 10,  0,  8],
       [ 7,  5,  6, 12]])

In [75]:
a.ravel()

array([19, 15, 17,  1, 17, 10,  0,  8,  7,  5,  6, 12])

In [76]:
a.flatten()   # both gives same results more details will learn in deep learning

array([19, 15, 17,  1, 17, 10,  0,  8,  7,  5,  6, 12])

# Universal Functions
For function like /,*,+,- of matrix

In [78]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)
# two matrix with same data gives different values
print("Matrix 1\n",mat1)
print("\nMatrix 2\n",mat2)

Matrix 1
 [[5 5 4]
 [4 4 9]
 [8 5 4]]

Matrix 2
 [[2 8 9]
 [2 1 8]
 [6 1 6]]


In [79]:
print(mat1+mat2)

[[ 7 13 13]
 [ 6  5 17]
 [14  6 10]]


In [80]:
print(mat1*mat2)

[[10 40 36]
 [ 8  4 72]
 [48  5 24]]


# Broadcasting

In [82]:
start=np.zeros((3,3))
start   # matriz 1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [84]:
add_row=np.array([[1,0,2]])
add_row   # matrix 2

array([[1, 0, 2]])

In [85]:
test1=start+add_row
test1

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [86]:
new_row=add_row.T   # .T is transpose which convert row into column and column into eow
new_row

array([[1],
       [0],
       [2]])

In [87]:
test2=new_row+start
test2

array([[1., 1., 1.],
       [0., 0., 0.],
       [2., 2., 2.]])